import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, symlinkSync, lstatSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { gitBlobSha, localSkillHashes, upstreamSkillHashes, classifySkill, materializeSkill, applySkill } from './skill-sync.mjs';

/** existsSync 会跟着软链走（断链返回 false），判断"这个目录项还在不在"必须用 lstat */
function entryExists(p) {
  try { lstatSync(p); return true; } catch { return false; }
}

describe('gitBlobSha', () => {
  // 期望值来自 `git hash-object --stdin`，与 git 自身一致
  it('matches git hash-object for an empty file', () => {
    expect(gitBlobSha(Buffer.from(''))).toBe('e69de29bb2d1d6434b8b29ae775ad8c2e48c5391');
  });

  it('matches git hash-object for ascii content', () => {
    expect(gitBlobSha(Buffer.from('hello\n'))).toBe('ce013625030ba8dba906f756967f9e9ca394464a');
  });

  it('matches git hash-object for utf-8 content (byte length, not char length)', () => {
    expect(gitBlobSha(Buffer.from('中文\n'))).toBe('0c3dd90b19be56e9cd94f052f74526aac2458521');
  });

  it('matches git hash-object for CRLF content (no newline translation)', () => {
    expect(gitBlobSha(Buffer.from('a\r\nb\r\n'))).toBe('c30dea8a3641ea99b125d04d599d843712292759');
  });
});

describe('localSkillHashes', () => {
  let dir;
  beforeEach(() => { dir = mkdtempSync(path.join(tmpdir(), 'cli-skill-')); });
  afterEach(() => { rmSync(dir, { recursive: true, force: true }); });

  it('returns {} when the directory does not exist', () => {
    expect(localSkillHashes(path.join(dir, 'nope'))).toEqual({});
  });

  it('hashes files recursively with posix-style relative paths', () => {
    writeFileSync(path.join(dir, 'SKILL.md'), 'hello\n');
    mkdirSync(path.join(dir, 'references'));
    writeFileSync(path.join(dir, 'references', 'a.md'), '');
    expect(localSkillHashes(dir)).toEqual({
      'SKILL.md': 'ce013625030ba8dba906f756967f9e9ca394464a',
      'references/a.md': 'e69de29bb2d1d6434b8b29ae775ad8c2e48c5391',
    });
  });

  it('skips .DS_Store (gitignored, regenerated by Finder — would show as spurious drift)', () => {
    writeFileSync(path.join(dir, 'SKILL.md'), 'hello\n');
    writeFileSync(path.join(dir, '.DS_Store'), 'junk');
    expect(Object.keys(localSkillHashes(dir))).toEqual(['SKILL.md']);
  });

  it('records a symlink with a sentinel sha instead of skipping it', () => {
    writeFileSync(path.join(dir, 'SKILL.md'), 'hello\n');
    symlinkSync(path.join(dir, 'SKILL.md'), path.join(dir, 'link.md'));
    const h = localSkillHashes(dir);
    // 被记下来了（漏掉就永远不会被判 removed / changed），而且值不可能等于任何真 blob sha
    expect(Object.keys(h).sort()).toEqual(['SKILL.md', 'link.md']);
    expect(h['link.md']).toBe('symlink');
    expect(h['link.md']).not.toBe(h['SKILL.md']);
  });

  it('records a dangling symlink without throwing (target 不存在也不能崩)', () => {
    symlinkSync(path.join(dir, 'nowhere.md'), path.join(dir, 'dangling.md'));
    expect(localSkillHashes(dir)).toEqual({ 'dangling.md': 'symlink' });
  });
});

describe('upstreamSkillHashes', () => {
  // 形如 GET /repos/<repo>/git/trees/<tag>?recursive=1 的 tree 数组
  const tree = [
    { path: 'skills', type: 'tree', sha: 'tttt' },
    { path: 'skills/fastpaper', type: 'tree', sha: 'uuuu' },
    { path: 'skills/fastpaper/SKILL.md', type: 'blob', sha: 'aaaa' },
    { path: 'skills/fastpaper/references/x.md', type: 'blob', sha: 'bbbb' },
    { path: 'skills/fastpaper/.DS_Store', type: 'blob', sha: 'ffff' },
    { path: 'skills/fastpaper-extra/SKILL.md', type: 'blob', sha: 'cccc' },
    { path: '.claude/skills/sync-docs/SKILL.md', type: 'blob', sha: 'dddd' },
    { path: 'README.md', type: 'blob', sha: 'eeee' },
  ];

  it('keeps only blobs strictly under repoPath, keyed by relative path', () => {
    expect(upstreamSkillHashes(tree, 'skills/fastpaper')).toEqual({
      'SKILL.md': 'aaaa',
      'references/x.md': 'bbbb',
    });
  });

  it('does not match a sibling dir sharing the prefix', () => {
    expect(upstreamSkillHashes(tree, 'skills/fastpaper-extra')).toEqual({ 'SKILL.md': 'cccc' });
  });

  it('returns {} when repoPath has no blobs', () => {
    expect(upstreamSkillHashes(tree, 'skills/nope')).toEqual({});
  });

  it('skips .DS_Store committed upstream', () => {
    expect(upstreamSkillHashes(tree, 'skills/fastpaper')['.DS_Store']).toBeUndefined();
  });

  it('rejects a traversing path from the tree', () => {
    const evil = [{ path: 'skills/fp/../escape.txt', type: 'blob', sha: 'aaaa' }];
    expect(() => upstreamSkillHashes(evil, 'skills/fp')).toThrow(/refusing to touch/);
  });
});

describe('classifySkill', () => {
  it('reports in-sync when every blob matches', () => {
    const r = classifySkill({ upstream: { 'SKILL.md': 'aaaa' }, local: { 'SKILL.md': 'aaaa' } });
    expect(r).toEqual({ status: 'in-sync', changed: [], added: [], removed: [] });
  });

  it('reports changed when content differs', () => {
    const r = classifySkill({ upstream: { 'SKILL.md': 'aaaa' }, local: { 'SKILL.md': 'zzzz' } });
    expect(r).toEqual({ status: 'differs', changed: ['SKILL.md'], added: [], removed: [] });
  });

  it('reports added for upstream-only files', () => {
    const r = classifySkill({
      upstream: { 'SKILL.md': 'aaaa', 'references/x.md': 'bbbb' },
      local: { 'SKILL.md': 'aaaa' },
    });
    expect(r).toEqual({ status: 'differs', changed: [], added: ['references/x.md'], removed: [] });
  });

  it('reports removed for local-only files', () => {
    const r = classifySkill({
      upstream: { 'SKILL.md': 'aaaa' },
      local: { 'SKILL.md': 'aaaa', 'stale.md': 'bbbb' },
    });
    expect(r).toEqual({ status: 'differs', changed: [], added: [], removed: ['stale.md'] });
  });

  it('treats a missing local dir as everything added', () => {
    const r = classifySkill({ upstream: { 'SKILL.md': 'aaaa', 'b.md': 'bbbb' }, local: {} });
    expect(r).toEqual({ status: 'differs', changed: [], added: ['SKILL.md', 'b.md'], removed: [] });
  });

  it('sorts each bucket', () => {
    const r = classifySkill({
      upstream: { 'c.md': '1', 'a.md': '2' },
      local: { 'c.md': 'x', 'a.md': 'y', 'z.md': '3', 'b.md': '4' },
    });
    expect(r.changed).toEqual(['a.md', 'c.md']);
    expect(r.removed).toEqual(['b.md', 'z.md']);
  });
});

describe('materializeSkill', () => {
  let dir;
  beforeEach(() => { dir = mkdtempSync(path.join(tmpdir(), 'cli-skill-mat-')); });
  afterEach(() => { rmSync(dir, { recursive: true, force: true }); });

  it('downloads each rel path under repoPath into tmpDir, creating parent dirs', async () => {
    const calls = [];
    const fetchFile = async (repo, tag, filePath) => {
      calls.push([repo, tag, filePath]);
      return Buffer.from(`body of ${filePath}`);
    };
    await materializeSkill({
      repo: 'o/r', tag: 'v1.0', repoPath: 'skills/fp',
      rels: ['SKILL.md', 'references/x.md'], tmpDir: dir, fetchFile,
    });
    expect(calls).toEqual([
      ['o/r', 'v1.0', 'skills/fp/SKILL.md'],
      ['o/r', 'v1.0', 'skills/fp/references/x.md'],
    ]);
    expect(readFileSync(path.join(dir, 'SKILL.md'), 'utf-8')).toBe('body of skills/fp/SKILL.md');
    expect(readFileSync(path.join(dir, 'references', 'x.md'), 'utf-8')).toBe('body of skills/fp/references/x.md');
  });

  it('refuses a traversing rel', async () => {
    const fetchFile = async () => Buffer.from('x');
    await expect(materializeSkill({
      repo: 'o/r', tag: 'v1.0', repoPath: 'skills/fp',
      rels: ['../escape.txt'], tmpDir: dir, fetchFile,
    })).rejects.toThrow(/refusing to touch/);
  });
});

describe('applySkill', () => {
  let src, dest;
  beforeEach(() => {
    src = mkdtempSync(path.join(tmpdir(), 'cli-skill-src-'));
    dest = mkdtempSync(path.join(tmpdir(), 'cli-skill-dest-'));
  });
  afterEach(() => {
    rmSync(src, { recursive: true, force: true });
    rmSync(dest, { recursive: true, force: true });
  });

  it('writes changed and added files, deletes removed ones', async () => {
    writeFileSync(path.join(src, 'SKILL.md'), 'new\n');
    mkdirSync(path.join(src, 'references'));
    writeFileSync(path.join(src, 'references', 'x.md'), 'added\n');
    writeFileSync(path.join(dest, 'SKILL.md'), 'old\n');
    writeFileSync(path.join(dest, 'stale.md'), 'bye\n');

    const r = await applySkill({
      srcDir: src,
      destAbs: dest,
      plan: { changed: ['SKILL.md'], added: ['references/x.md'], removed: ['stale.md'] },
    });

    expect(readFileSync(path.join(dest, 'SKILL.md'), 'utf-8')).toBe('new\n');
    expect(readFileSync(path.join(dest, 'references', 'x.md'), 'utf-8')).toBe('added\n');
    expect(existsSync(path.join(dest, 'stale.md'))).toBe(false);
    expect(r).toEqual({ written: 2, removed: 1 });
  });

  it('creates the dest dir when the skill is new', async () => {
    const fresh = path.join(dest, 'nested', 'fastpaper');
    writeFileSync(path.join(src, 'SKILL.md'), 'hi\n');
    await applySkill({ srcDir: src, destAbs: fresh, plan: { changed: [], added: ['SKILL.md'], removed: [] } });
    expect(readFileSync(path.join(fresh, 'SKILL.md'), 'utf-8')).toBe('hi\n');
  });

  it('prunes directories left empty by removals, but keeps dest itself', async () => {
    mkdirSync(path.join(dest, 'references'));
    writeFileSync(path.join(dest, 'references', 'x.md'), 'bye\n');
    await applySkill({ srcDir: src, destAbs: dest, plan: { changed: [], added: [], removed: ['references/x.md'] } });
    expect(existsSync(path.join(dest, 'references'))).toBe(false);
    expect(existsSync(dest)).toBe(true);
  });

  it('refuses to write outside destAbs', async () => {
    writeFileSync(path.join(src, 'escape.txt'), 'evil\n');
    await expect(applySkill({
      srcDir: src, destAbs: dest,
      plan: { changed: [], added: ['../escape.txt'], removed: [] },
    })).rejects.toThrow(/refusing to touch/);
    expect(existsSync(path.join(dest, '..', 'escape.txt'))).toBe(false);
  });

  it('refuses to delete outside destAbs, without having written anything first', async () => {
    const outside = path.join(dest, '..', 'victim.txt');
    writeFileSync(outside, 'keep me\n');
    writeFileSync(path.join(src, 'SKILL.md'), 'new\n');
    await expect(applySkill({
      srcDir: src, destAbs: dest,
      plan: { changed: [], added: ['SKILL.md'], removed: ['../victim.txt'] },
    })).rejects.toThrow(/refusing to touch/);
    expect(existsSync(outside)).toBe(true);
    expect(existsSync(path.join(dest, 'SKILL.md'))).toBe(false);   // 校验先于写入
    rmSync(outside, { force: true });
  });

  it('refuses an absolute rel', async () => {
    await expect(applySkill({
      srcDir: src, destAbs: dest,
      plan: { changed: [], added: [path.join(src, 'SKILL.md')], removed: [] },
    })).rejects.toThrow(/refusing to touch/);
  });

  it('refuses a rel with an empty segment', async () => {
    await expect(applySkill({
      srcDir: src, destAbs: dest,
      plan: { changed: [], added: ['references//x.md'], removed: [] },
    })).rejects.toThrow(/refusing to touch/);
  });
});

/**
 * dest 是纯 vendor 副本，里面不该有软链。软链既能让写入跟着链跑到目录外，
 * 又会因为不进 local 而永远删不掉——这组用例盯的是"目录外的真身没被动过"。
 */
describe('applySkill × 软链', () => {
  let src, dest, outside;
  beforeEach(() => {
    src = mkdtempSync(path.join(tmpdir(), 'cli-skill-src-'));
    dest = mkdtempSync(path.join(tmpdir(), 'cli-skill-dest-'));
    outside = mkdtempSync(path.join(tmpdir(), 'cli-skill-outside-'));
  });
  afterEach(() => {
    for (const d of [src, dest, outside]) rmSync(d, { recursive: true, force: true });
  });

  it('上游有同名文件时判 changed，写入落在 dest 里而不是链外的真身上', async () => {
    const victim = path.join(outside, 'victim.txt');
    writeFileSync(victim, 'keep me\n');
    symlinkSync(victim, path.join(dest, 'SKILL.md'));
    writeFileSync(path.join(src, 'SKILL.md'), 'upstream\n');

    const upstream = { 'SKILL.md': gitBlobSha(Buffer.from('upstream\n')) };
    const plan = classifySkill({ upstream, local: localSkillHashes(dest) });
    expect(plan).toEqual({ status: 'differs', changed: ['SKILL.md'], added: [], removed: [] });

    await applySkill({ srcDir: src, destAbs: dest, plan });

    // 关键断言：链外的真身一个字节都没变
    expect(readFileSync(victim, 'utf-8')).toBe('keep me\n');
    // 而 dest 里的那一项已经是真文件（不再是链），内容是上游的
    expect(lstatSync(path.join(dest, 'SKILL.md')).isSymbolicLink()).toBe(false);
    expect(readFileSync(path.join(dest, 'SKILL.md'), 'utf-8')).toBe('upstream\n');
  });

  it('上游没有同名文件时判 removed，删掉链本身而不是它指向的文件', async () => {
    const victim = path.join(outside, 'victim.txt');
    writeFileSync(victim, 'keep me\n');
    symlinkSync(victim, path.join(dest, 'stale.md'));
    writeFileSync(path.join(dest, 'SKILL.md'), 'same\n');

    const upstream = { 'SKILL.md': gitBlobSha(Buffer.from('same\n')) };
    const plan = classifySkill({ upstream, local: localSkillHashes(dest) });
    expect(plan).toEqual({ status: 'differs', changed: [], added: [], removed: ['stale.md'] });

    await applySkill({ srcDir: src, destAbs: dest, plan });

    expect(entryExists(path.join(dest, 'stale.md'))).toBe(false);
    expect(existsSync(victim)).toBe(true);
    expect(readFileSync(victim, 'utf-8')).toBe('keep me\n');
  });
});
