import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { gitBlobSha, localSkillHashes, upstreamSkillHashes, classifySkill } from './skill-sync.mjs';

describe('gitBlobSha', () => {
  // 期望值来自 `git hash-object --stdin`，与 git 自身一致
  it('matches git hash-object for an empty file', () => {
    expect(gitBlobSha(Buffer.from(''))).toBe('e69de29bb2d1d6434b8b29ae775ad8c2e48c5391');
  });

  it('matches git hash-object for ascii content', () => {
    expect(gitBlobSha(Buffer.from('hello\n'))).toBe('ce013625030ba8dba906f756967f9e9ca394464a');
  });

  it('matches git hash-object for utf-8 content (byte length, not char length)', () => {
    expect(gitBlobSha(Buffer.from('中文\n'))).toBe('0c3dd90b19be56e9cd94f052f74526aac2458521');
  });

  it('matches git hash-object for CRLF content (no newline translation)', () => {
    expect(gitBlobSha(Buffer.from('a\r\nb\r\n'))).toBe('c30dea8a3641ea99b125d04d599d843712292759');
  });
});

describe('localSkillHashes', () => {
  let dir;
  beforeEach(() => { dir = mkdtempSync(path.join(tmpdir(), 'cli-skill-')); });
  afterEach(() => { rmSync(dir, { recursive: true, force: true }); });

  it('returns {} when the directory does not exist', () => {
    expect(localSkillHashes(path.join(dir, 'nope'))).toEqual({});
  });

  it('hashes files recursively with posix-style relative paths', () => {
    writeFileSync(path.join(dir, 'SKILL.md'), 'hello\n');
    mkdirSync(path.join(dir, 'references'));
    writeFileSync(path.join(dir, 'references', 'a.md'), '');
    expect(localSkillHashes(dir)).toEqual({
      'SKILL.md': 'ce013625030ba8dba906f756967f9e9ca394464a',
      'references/a.md': 'e69de29bb2d1d6434b8b29ae775ad8c2e48c5391',
    });
  });

  it('skips .DS_Store (gitignored, regenerated by Finder — would show as spurious drift)', () => {
    writeFileSync(path.join(dir, 'SKILL.md'), 'hello\n');
    writeFileSync(path.join(dir, '.DS_Store'), 'junk');
    expect(Object.keys(localSkillHashes(dir))).toEqual(['SKILL.md']);
  });
});

describe('upstreamSkillHashes', () => {
  // 形如 GET /repos/<repo>/git/trees/<tag>?recursive=1 的 tree 数组
  const tree = [
    { path: 'skills', type: 'tree', sha: 'tttt' },
    { path: 'skills/fastpaper', type: 'tree', sha: 'uuuu' },
    { path: 'skills/fastpaper/SKILL.md', type: 'blob', sha: 'aaaa' },
    { path: 'skills/fastpaper/references/x.md', type: 'blob', sha: 'bbbb' },
    { path: 'skills/fastpaper/.DS_Store', type: 'blob', sha: 'ffff' },
    { path: 'skills/fastpaper-extra/SKILL.md', type: 'blob', sha: 'cccc' },
    { path: '.claude/skills/sync-docs/SKILL.md', type: 'blob', sha: 'dddd' },
    { path: 'README.md', type: 'blob', sha: 'eeee' },
  ];

  it('keeps only blobs strictly under repoPath, keyed by relative path', () => {
    expect(upstreamSkillHashes(tree, 'skills/fastpaper')).toEqual({
      'SKILL.md': 'aaaa',
      'references/x.md': 'bbbb',
    });
  });

  it('does not match a sibling dir sharing the prefix', () => {
    expect(upstreamSkillHashes(tree, 'skills/fastpaper-extra')).toEqual({ 'SKILL.md': 'cccc' });
  });

  it('returns {} when repoPath has no blobs', () => {
    expect(upstreamSkillHashes(tree, 'skills/nope')).toEqual({});
  });

  it('skips .DS_Store committed upstream', () => {
    expect(upstreamSkillHashes(tree, 'skills/fastpaper')['.DS_Store']).toBeUndefined();
  });
});

describe('classifySkill', () => {
  it('reports in-sync when every blob matches', () => {
    const r = classifySkill({ upstream: { 'SKILL.md': 'aaaa' }, local: { 'SKILL.md': 'aaaa' } });
    expect(r).toEqual({ status: 'in-sync', changed: [], added: [], removed: [] });
  });

  it('reports changed when content differs', () => {
    const r = classifySkill({ upstream: { 'SKILL.md': 'aaaa' }, local: { 'SKILL.md': 'zzzz' } });
    expect(r).toEqual({ status: 'differs', changed: ['SKILL.md'], added: [], removed: [] });
  });

  it('reports added for upstream-only files', () => {
    const r = classifySkill({
      upstream: { 'SKILL.md': 'aaaa', 'references/x.md': 'bbbb' },
      local: { 'SKILL.md': 'aaaa' },
    });
    expect(r).toEqual({ status: 'differs', changed: [], added: ['references/x.md'], removed: [] });
  });

  it('reports removed for local-only files', () => {
    const r = classifySkill({
      upstream: { 'SKILL.md': 'aaaa' },
      local: { 'SKILL.md': 'aaaa', 'stale.md': 'bbbb' },
    });
    expect(r).toEqual({ status: 'differs', changed: [], added: [], removed: ['stale.md'] });
  });

  it('treats a missing local dir as everything added', () => {
    const r = classifySkill({ upstream: { 'SKILL.md': 'aaaa', 'b.md': 'bbbb' }, local: {} });
    expect(r).toEqual({ status: 'differs', changed: [], added: ['SKILL.md', 'b.md'], removed: [] });
  });

  it('sorts each bucket', () => {
    const r = classifySkill({
      upstream: { 'c.md': '1', 'a.md': '2' },
      local: { 'c.md': 'x', 'a.md': 'y', 'z.md': '3', 'b.md': '4' },
    });
    expect(r.changed).toEqual(['a.md', 'c.md']);
    expect(r.removed).toEqual(['b.md', 'z.md']);
  });
});
